#!/bin/bash
cd ${0%/*} || exit 1

basic/Allwclean
transport/Allwclean
reactiveTransport/Allwclean
multiphase/Allwclean
multiphaseTransport/Allwclean
multiphaseReactiveTransport/Allwclean
incompressible/Allwclean
heatTransfer/Allwclean
