rm -rf [1-9]*
rm -f *Flow.out
rm -rf processor*/[1-9]*
rm -f 0/phi
rm -f 0/U
rm -rf 0/p
rm -rf 0/Kinv
rm -rf processor*/0/phi
rm -rf processor*/0/p
rm -rf processor*/0/p
rm -rf processor*/0/Kinv
rm -f poroPerm.csv
rm -f system/SPDict
