#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmake reactiveTransportFoam
wmake reactiveTransportALEFoam
wmake reactiveTransportDBSFoam
# ----------------------------------------------------------------- end-of-file
