#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

thermophysicalModels/Allwmake
wmake libso fvMotionSolver
wmake libso finiteVolume
wmake libso meshTools
transportModels/Allwmake
# ----------------------------------------------------------------- end-of-file
